name: Flutter Build Android APK
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取项目源码
        uses: actions/checkout@v4

      - name: 安装Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'
          channel: 'stable'

      - name: 进入Flutter应用目录并安装依赖
        run: |
          cd simple_live_app
          flutter pub get

      - name: 构建Android正式版APK
        run: |
          cd simple_live_app
          flutter build apk --release --no-tree-shake-icons

      - name: 上传编译好的APK
        uses: actions/upload-artifact@v4
        with:
          name: dart-simple-live-android-apk
          path: simple_live_app/build/app/outputs/flutter-apk/app-release.apk
